name: Build and upload release binary

on:
  push:
    tags:
      - "v*.*.*"
  pull_request: {}

jobs:
  release:
    strategy:
      matrix:
        compile:
          - name: Alpine (x86_64)
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - name: Alpine (arm64)
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - name: Ubuntu (x86_64)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: Ubuntu (arm64)
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: MacOS (x86_64)
            os: macOS-latest
            target: x86_64-apple-darwin
          - name: MacOS (arm64)
            os: macOS-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.compile.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.compile.target }}
          override: true
      - name: Configure ${{ matrix.compile.name }}
        if: ${{ matrix.compile.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu
          # Ref: https://github.com/napi-rs/node-rs/blob/main/.cargo/config.toml
          echo '[target.aarch64-unknown-linux-gnu]' > ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml
          # Ref: https://github.com/rust-lang/rust/issues/46651#issuecomment-433611633
          echo '[target.aarch64-unknown-linux-musl]' >> ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml
          echo 'rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc" ]' >> ~/.cargo/config.toml
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.compile.target }} --features vendored -v
      - name: Rename
        run: mv target/${{ matrix.compile.target }}/release/vault-k8s-helper vault-k8s-helper-${{ matrix.compile.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vault-k8s-helper-${{ matrix.compile.target }}
