name: Build and upload release binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        target:
          # - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          # - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Configure gcc
        run: |
          # Ref: https://github.com/napi-rs/node-rs/blob/main/.cargo/config.toml
          sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu
          echo '[target.aarch64-unknown-linux-gnu]' > ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }} --features vendored -v
      - name: Rename
        run: mv target/${{ matrix.target }}/release/vault-k8s-helper vault-k8s-helper-${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vault-k8s-helper-${{ matrix.target }}
